import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { Metadata } from 'next';
import { AlertTriangle, ShieldCheck, FileText, Scale } from 'lucide-react';

export const metadata: Metadata = {
    title: 'Disclaimer - Terms of Use & Liability | FreeToolsHub',
    description: 'Read the FreeToolsHub disclaimer regarding the accuracy of tools, liability limitations, and the nature of our free online services.',
};

export default function DisclaimerPage() {
    return (
        <div className="min-h-screen flex flex-col bg-surface-50 dark:bg-surface-950">
            <Header />

            <main className="flex-grow pt-32 pb-20 container mx-auto px-4 max-w-4xl space-y-12">
                <section className="text-center space-y-4">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-500/10 text-amber-500 text-xs font-bold mb-4 uppercase tracking-widest">
                        <AlertTriangle size={14} /> Legal Notice
                    </div>
                    <h1 className="text-5xl md:text-6xl font-black font-outfit tracking-tight">
                        Disclaimer
                    </h1>
                    <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
                        Please read this disclaimer carefully before using the tools and services provided by FreeToolsHub.
                    </p>
                </section>

                <div className="glass-card p-8 md:p-12 space-y-10 text-muted-foreground leading-relaxed">
                    <div className="space-y-4">
                        <h2 className="text-2xl font-bold font-outfit text-foreground flex items-center gap-3">
                            <ShieldCheck className="text-emerald-500" />
                            1. Accuracy of Tools
                        </h2>
                        <p>
                            The tools and calculators provided on FreeToolsHub are for informational and convenience purposes only. While we strive to ensure the highest degree of accuracy, we do not guarantee that the results generated by our tools are error-free, complete, or current.
                        </p>
                        <p>
                            Users are encouraged to verify critical results (such as financial calculations, unit conversions for engineering, or time-sensitive data) with official or professional sources.
                        </p>
                    </div>

                    <div className="space-y-4">
                        <h2 className="text-2xl font-bold font-outfit text-foreground flex items-center gap-3">
                            <Scale className="text-blue-500" />
                            2. Limitation of Liability
                        </h2>
                        <p>
                            FreeToolsHub, its owners, and contributors shall not be held liable for any direct, indirect, incidental, consequential, or exemplary damages arising from your use of, or inability to use, our services. This includes, but is not limited to, damages for loss of profits, data, or other intangible losses.
                        </p>
                    </div>

                    <div className="space-y-4">
                        <h2 className="text-2xl font-bold font-outfit text-foreground flex items-center gap-3">
                            <FileText className="text-purple-500" />
                            3. No Professional Advice
                        </h2>
                        <p>
                            The information provided by our tools does not constitute professional advice (financial, legal, medical, or otherwise). Use of this website does not create a professional-client relationship.
                        </p>
                    </div>

                    <div className="space-y-4">
                        <h2 className="text-2xl font-bold font-outfit text-foreground">
                            4. Third-Party Links
                        </h2>
                        <p>
                            Our website may contain links to third-party websites or services that are not owned or controlled by FreeToolsHub. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites.
                        </p>
                    </div>

                    <div className="pt-8 border-t">
                        <p className="text-sm italic">
                            By using FreeToolsHub, you hereby consent to our disclaimer and agree to its terms. If you do not agree with any part of this disclaimer, you must discontinue the use of our website immediately.
                        </p>
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
}
